### ISSUE TITLE
Documentation for volume mounts

### ISSUE THREAD

**Issue by tineambracken** [origamiofficial/docker-pihole-unbound#20]
Hello @origamiofficial ,

I decided to bail on the `chriscrowe/docker-pihole-unbound` project due to it _appearing_ to be abandoned - several open (and older) repository issues, outdated docker tag, etc.  

Please bear with my inquiry as I am still learning.  While I don't have an issue, I do have a couple questions regarding transitioning to this repository:

1.  Apologies if I've missed this in the README, but I did not see the list of volume mounts to be used.  I'd like to confirm that the paths used in the chriscrowe version are the same as in `rlabinc/pihole-unbound`:
```
-v /pihole/:/etc/pihole/ 
-v /dnsmasq.d/:/etc/dnsmasq.d/
```
2. Additionally, with the chriscrowe version, I had not used the `unbound.conf` file so the `/opt/unbound/etc/unbound` directory was not mounted in that installation.  Is this volume and configuration required or do the masses just recommend its inclusion?

Thanks in advance,
Christine

**Comment by origamiofficial** [comment]
Hi @tineambracken,
Thanks for giving a shot to this image.

Q1 Ans: Yes! the paths used in the chriscrowe version are the same as this one. The path you're talking about is from the official Pi-hole image itself. We never touch them at all while building this image. So, unless the Pi-hole team decides to move, all of your mentioned paths will be there. It also is applied for all the images that use the official Pi-hole image as the base image.

Q2 Ans: You don't need to mount `/opt/unbound/etc/unbound` unless you want to replace the Unbound config file known as `unbound.conf`. It's for users who want to use a custom Unbound config of their own instead of the one shipped with.

**Comment by tineambracken** [comment]
@origamiofficial thanks for the swift and thorough reply!  

Kindly,
Christine
